site_name: Essential AI
nav:
  - Essential AI Home:
      - 'What is Essential AI': index.md
      - 'About Me': about.md
      - 'Portfolio Optimization using Reinforcement Learning': our_notebook_final.md
  - Computer Vision and Image Processing:
      - 'Introduction': Computer_Vision_and_Image_Processing/index.md

theme:
  name: material
  font:
    text: Andika

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.top
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        # primary: teal
        # accent: purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        # primary: teal
        # accent: purple
  language: en
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - glightbox

repo_url: https://github.com/EssentialAI/essentialai.github.io
repo_name: EssentialAI

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
        #   features:
        #     # - navigation.tabs
        #     - navigation.sections
        #     # - toc.integrate
        #     # - navigation.top
        #     - search.suggest
        #     - search.highlight
        #     - content.tabs.link
        #     - content.code.annotation
        #     - content.code.copy
        #   language: en
        #   palette:
        #     - scheme: default
        #       toggle:
        #         icon: material/white-balance-sunny
        #         name: Switch to dark mode
        #       # primary: teal
        #       accent: purple
        #     - scheme: slate
        #       toggle:
        #         icon: material/moon-last-quarter
        #         name: Switch to light mode
        #       # primary: teal
        #       accent: lime
        # # plugins:
        # #   - social
        # # extra:
        # #   social:
        # #     - icon: material/moon-last-quarter
        # #       link: https://github.com/james-willett
        # #     - icon: material/moon-last-quarter
        # #       link: https://twitter.com/TheJamesWillett
        # #     - icon: material/moon-last-quarter
        # #       link: https://www.linkedin.com/in/willettjames/
        # markdown_extensions:
        #   - pymdownx.highlight:
        #       anchor_linenums: true
        #   - pymdownx.inlinehilite
        #   - pymdownx.snippets
        #   - admonition
        #   - pymdownx.arithmatex:
        #       generic: true
        #   - footnotes
        #   - pymdownx.details
        #   - pymdownx.superfences
        #   - pymdownx.mark
        #   - attr_list
        #   - pymdownx.emoji:
        #       emoji_index: !!python/name:materialx.emoji.twemoji
        #       emoji_generator: !!python/name:materialx.emoji.to_svg


