/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    "intro",
    "about",
    {
      type: 'category',
      label: 'Essential AI blog',
      collapsed: false,
      items: ['mnist-4-neurons'],
    },

    {
      type: 'category',
      label: "Machine Learning Explained",
      collapsed: true,
      items: ['ML/linear-regression'],
    },
    // {
    //   type: 'category',
    //   label: "My DS Algo Experience",
    //   collapsed: false,
    //   items: ['ds-algo/l_intro'],
    // },
    {
      type: 'category',
      label: "My Data Science Notes",
      collapsed: true,
      items: [{
        type: 'category',
        label: "Machine learning Zoomcamp",
        collapsed: true,
        items: ['ML_zoomcamp/zoomcamp_intro', 'ML_zoomcamp/supervised-ml'],
      }],
    },
    {
      type: 'category',
      label: 'DS Algos',
      collapsed: true,
      items: ['ds-algo/l_intro', 'ds-algo/arrays-easy'],
    },

    // {
    //   type: 'category',
    //   label: "Data Science journey",
    //   collapsed: true,
    //   items: [{
    //     type: 'category',
    //     label: "SQL",
    //     collapsed: false,
    //     items: ['SQL/s_intro','SQL/s_installation'],
    //   }],
    // },

    // {
    //   type: 'category',
    //   label: 'Research',
    //   collapsed: false,
    //   items: ['momentum'],
    // },
  ],
};

module.exports = sidebars;
