/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    "intro",
    {
      type: 'category',
      label: 'Essential AI articles',
      collapsed: true,
      items: ['mnist-4-neurons', 'taylor-approximation'],
    },
    {
      type: 'category',
      label: "Explain Machine Learning like I'm 10",
      collapsed: true,
      items: ['ML/linear-regression'],
    },
    {
      type: 'category',
      label: "My DS Algo Experience",
      collapsed: false,
      items: ['ds-algo/l_intro'],
    },

    // {
    //   type: 'category',
    //   label: "Data Science journey",
    //   collapsed: true,
    //   items: [{
    //     type: 'category',
    //     label: "SQL",
    //     collapsed: false,
    //     items: ['SQL/s_intro','SQL/s_installation'],
    //   }],
    // },

    // {
    //   type: 'category',
    //   label: 'Research',
    //   collapsed: false,
    //   items: ['momentum'],
    // },
  ],
};

module.exports = sidebars;
